// <auto-generated />
namespace FirstTeachersProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpdatedChildClonemethodtoincludeActiveDateCreatedandDateUpdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdatedChildClonemethodtoincludeActiveDateCreatedandDateUpdated));
        
        string IMigrationMetadata.Id
        {
            get { return "201707211546409_Updated Child.Clone method to include Active, DateCreated, and DateUpdated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
