// <auto-generated />
namespace FirstTeachersProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addadminaccountondbinit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addadminaccountondbinit));
        
        string IMigrationMetadata.Id
        {
            get { return "201707142030376_add-admin-account-on-db-init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
